# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # set to false, if you do NOT want to check the correct VirtualBox Guest Additions version when booting this box
  if defined?(VagrantVbguest::Middleware)
    config.vbguest.auto_update = true
  end
  
  config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--cpus", "2", "--memory", "512"]
  end

  config.vm.define :elastalert do |elastalert_config|
  	
  	elastalert_config.vm.box = "ubuntu/trusty64"
    elastalert_config.vm.hostname = 'elastalert' 
    elastalert_config.vm.network :private_network, ip: "172.28.1.11" 
    elastalert_config.vm.network :forwarded_port, guest: 9400, host: 9400
    elastalert_config.vm.network :forwarded_port, guest:5000 , host: 5000

    elastalert_config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
  	elastalert_config.vm.provision :shell, path: "provision-elastalert.sh"
    elastalert_config.vm.provision :shell, path: "provision-demo.sh"
  end

end

